Adding info about Scenario
Codeception/module-webdriver pull request #37
Opened 2020-11-19 09:43 UTC by ThomasLandauer

See https://github.com/Codeception/Codeception/issues/6035

TODO: Update the anchor after https://github.com/Codeception/codeception.github.com/pull/378 is online

2021-01-09 23:51 UTC, ThomasLandauer commented
The anchor is OK, so the above TODO is done.

2021-01-17 19:21 UTC, Naktibalda requested changes

2021-01-17 19:21 UTC, Naktibalda commented on src/Codeception/Module/WebDriver.php
> + * You can switch between browsers inside your code by injecting `\Codeception\Scenario` into your test like this:
This sentence doesn't make sense to me.

In order to change browsers you have to use
```php
$this->getModule('WebDriver')->_restart(['browser' => $browser]);
```
as documented at https://codeception.com/docs/modules/WebDriver#_restart

2021-03-16 16:36 UTC, ThomasLandauer commented on src/Codeception/Module/WebDriver.php
> + * You can switch between browsers inside your code by injecting `\Codeception\Scenario` into your test like this:
The idea was to show some example for scenario, see https://github.com/Codeception/Codeception/issues/6035#issuecomment-730257318 - and I couldn't think of another use case as switching the browser ;-)

I now added your line - but will `$this->getModule(...)` work from within a test at all? Or do I have to think of another use case...?

2021-03-16 16:55 UTC, Naktibalda commented on src/Codeception/Module/WebDriver.php
> + * You can switch between browsers inside your code by injecting `\Codeception\Scenario` into your test like this:
`getModule` method is not accessible in test code, it can only be used in helpers.

2021-03-16 17:37 UTC, ThomasLandauer commented
I deleted my fork, so I had to start from scratch :-) See https://github.com/Codeception/module-webdriver/pull/65

2021-03-16 17:37 UTC, closed without merging